# .goreleaser.yml

project_name: logbook-go

env:
  - GO111MODULE=on

# Build destination
github_urls:
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

before:
  hooks:
    - ./scripts/build.sh

builds:
- skip: true

release:
  prerelease: auto
