openapi: "3.0.3"
info:
  version: 0.1.0
  title: Logbook API
  description: Client for Logbook API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
paths:
  /api/v1/divelogs:
    $ref: './paths/divelogs.yaml'
  /api/v1/divelog/{divelogId}:
    $ref: './paths/divelog/{divelogId}.yaml'
  /api/v1/admin/health:
    $ref: './paths/admin/health.yaml'
